server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/longxiweijing?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    #url: jdbc:mysql://119.2.7.45:3307/longxiweijing?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456
    #password: yuntu@163
    driver-class-name: com.mysql.jdbc.Driver
    validationQuery: SELECT 1 FROM DUAL
  rabbitmq:
    #host: 10.129.6.251
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    #password: admin
    publisher-confirms: true
    publisher-returns: true

    listener:
      simple:
        acknowledge-mode: manual #采用手动应答模式；
        concurrency: 1 #指定最小的消费数量；
        max-concurrency: 1 #指定最大的消费数量；
        retry:
          enabled: true
  #redis 配置
  redis:
    database: 0
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password:
    port: 6379

alipay:
  apikey: "00014005"

admin:
  adress: http://10.129.6.250:8090/roomimg/getImages?path=
qrDir: D:/

mybatis-plus:
  mapper-locations: classpath*:com/mapper/xml/*.xml
  global-config:
    banner: false
    db-config:
      id-type: 4
      table-underline: true

#sdk 发卡机 串口
sdk:
  ComHandle: 5 #发卡器串口
#  ComHandle: 1 #发卡机串口
#读卡器  串口
sdk1:
  ComHandle: 7

dapuPort: 7

print:
  hotelname: 龙熙维景国际会议中心
  phone: 010-53876999
  leave: 12:00
  wifiname: ceshi
  wifipass: 18888888

  #图片路径
  imgurl: E:\\Thelog\\ceshi.jpg
Invoiqr:
  #由电子发票平台分配的appCode
  #appCode: PTTEST17 #测试
  appCode: PT000097 #生产
  #调用方纳税人识别号
  #taxpayerCode: 91370200264807TEST4A  #测试
  taxpayerCode: 91110115355261525F  #生产
  #证书路径
  #keyStorePath: D:/PTTEST17.keystore #测试
  keyStorePath: D:/PT000097.keystore #生产
  #证书别名
  #keyStoreAbner: PTTEST17 #测试
  keyStoreAbner: 9hnjuy # 生产
  #证书密码
  #keyStorePassWord: PTTEST17  #测试
  keyStorePassWord: gst6ybgs  #生产
  #发票接口
  #facadeUrl: https://www.chinaeinv.com:943/igs/api/orderApi.jspa  #测试
  facadeUrl: https://www.chinaeinv.com/igs/api/orderApi.jspa  #生产


#人证合一 实时人像图片留存地址
timeImgUrl: D:\\image\\


logoimgUrl: D:\\bill\\logo.png
pdfUrl: D:\\bill\\
reservationMonthUrl: D:\\reservation\\
operRecordMonthUrl: D:\\operrecord\\

Email:
  #个人HOST
  HOST: smtp.163.com
  #企业HOST
  #HOST: smtphz.qiye.163.com
  FROM: chunshangzzj@163.com
  USER: chunshangzzj@163.com
  PWD: VKERLWISVDJMGNUG
  SUBJECT: 邮件
  AFFIXNAME: pdf.pdf
  cardEmail: 570148135@qq.com
  #cardEmail: 1005454850@qq.com
  #reservationEmail: 570148135@qq.com
  reservationEmail: 1005454850@qq.com